- SyntheticsRunTestsTask/__tests__/fixtures.ts
If you forget to run `yarn build` before `yarn test` in a clean repository without any compiled files, you'll have errors like:
```
expect(received).toContainEqual(expected) // deep equality
Expected value: [Anything, {"apiKey": "xxx", "appKey": "yyy", "configPath": "datadog-ci.json", "datadogSite": "datadoghq.eu", "failOnCriticalErrors": false, "failOnTimeout": false, "files": ["{,!(node_modules)/**/}*.synthetics.json"], "global": {}, "locations": [], "pollingTimeout": 120000, "proxy": {"protocol": "http"}, "publicIds": ["public_id1", "public_id2", "public_id3"], "subdomain": "myorg", "tunnel": false, "variableStrings": []}]
Received array: []
99 |     const logs: unknown[] = spyLogs.map(log => JSON.parse(log.replace(prefixMatcher, '')))
100 |
> 101 | …
```
> Ensure js file exists before running a mocked task

- azure-pipelines.yml
- ci/e2e.azure-pipelines.yml
This PR provide an additional pipeline to run true end-to-end tests using a DEV private extension:
- Add job to publish DEV extension:
- Runs from `main` merges, or manual runs from any branch
- The `datadog-ci-dev` extension is published privately to the datadog-ci org
- Release is automatically bumped to the the next patch version, task ID is also updated
- Create E2E pipeline to run the Synthetics task:
- Triggered manually only
- Use the full task id `Datadog.datadog-ci-dev.synthetics-application-testing.SyntheticsRunTests@0` to differentiate with the production task
- Run tests with both API keys authentication and connected service
> [ci] Publish DEV private extension, Create end-to-end tests

- SyntheticsRunTestsTask/__tests__/fixtures.ts
- SyntheticsRunTestsTask/package.json
- SyntheticsRunTestsTask/resolve-config.ts
- SyntheticsRunTestsTask/yarn.lock
This PR bumps `datadog-ci` to [release v1.16.0](https://github.com/DataDog/datadog-ci/releases/tag/v1.16.0).
> Bump datadog-ci to 1.16.0

- SyntheticsRunTestsTask/task.json
- SyntheticsRunTestsTask/task.node10.ts
- **Based on https://github.com/DataDog/datadog-ci-azure-devops/pull/27**
(Re)Add support for `Node10`execution handler flagged as legacy, the task is still executed but a warning is emitted.
The warning will show up in the pipeline and the task logs:
This will be mentioned in the Github release notes.
> [dep] `SyntheticsRunTestsTask`: Node10 legacy support

- SyntheticsRunTestsTask/package.json
- SyntheticsRunTestsTask/task.json
- SyntheticsRunTestsTask/yarn.lock
This PR bumps `datadog-ci` to [release v2.2.0](https://github.com/DataDog/datadog-ci/releases/tag/v2.2.0).
> Bump datadog-ci to 2.2.0

- azure-pipelines.yml
Following the migration to Yarn 3 (#42), the "Release DEV Publish DEV version" [job started failing](https://datadog-ci.visualstudio.com/Datadog%20CI%20Azure%20DevOps%20Extension/_build/results?buildId=518&view=logs&j=8a5e36fb-d34d-5540-eed9-70d1ef2de729&t=afe13ce5-d1dd-5c0d-ab96-b4c54c0d0d39) with:
> error: Extension package is malformed/corrupted
>
> ##[error]tfx failed with error: Error: The process '/opt/hostedtoolcache/tfx/0.12.0/x64/bin/tfx' failed with exit code 255
A related issue exists on the repository for the `tfx` CLI: https://github.com/Microsoft/tfs-cli/issues/133
But the issue is still open.
So, since we can't ignore files with the CLI we need to remove the `.yarn` folder (contains cache for the `node_modules`) before packaging the `.vsix` file.
> [package] Exclude `.yarn` folder

- SyntheticsRunTestsTask/__tests__/fixtures.ts
- SyntheticsRunTestsTask/__tests__/mocks/api-keys.ts
- SyntheticsRunTestsTask/__tests__/mocks/junit-report.ts
- SyntheticsRunTestsTask/__tests__/mocks/service-connection-env-vars.ts
- SyntheticsRunTestsTask/__tests__/mocks/service-connection.ts
- SyntheticsRunTestsTask/resolve-config.ts
- SyntheticsRunTestsTask/utils.ts
- https://github.com/DataDog/datadog-ci-azure-devops/pull/41
- https://github.com/DataDog/datadog-ci-azure-devops/pull/42
- https://github.com/DataDog/datadog-ci-azure-devops/pull/44 ←
---
This PR replaces the local implementation of `removeUndefinedValues` with an import of `datadog-ci`'s one.
It also updates the test mocks accordingly, and adds some comments in `fixtures.ts`.
> Use `utils` exposed by datadog-ci

- README.md
Adds a site region shortcode in the doc page.
DOCS-5226
https://docs-staging.datadoghq.com/alai97/continuous-testing-cicd-integrations-site-region-update/continuous_testing/cicd_integrations/azure_devops_extension
> DOCS-5226 Azure DevOps Extension Edits

- LICENSE-3rdparty.csv
- SyntheticsRunTestsTask/package.json
- SyntheticsRunTestsTask/resolve-config.ts
- SyntheticsRunTestsTask/yarn.lock
- #46 
- #49 ←
---
The `clipanion` dependency was used to import the `BaseContext` interface only.
But we can just do pass `process` directly: `{ context: process}` (we do it [in datadog-ci](https://github.com/DataDog/datadog-ci/blob/e8f18c0030bf54ca6f81e00d58d60cb6718b6194/src/commands/synthetics/run-test.ts#L279)).
> Remove superfluous dependency

- SyntheticsRunTestsTask/yarn.lock
Even after upgrading datadog-ci (for which we fixed the security vulnerabilities), we still have `vm2@3.9.14` in this CI integration:
```
└─ synthetics-test-automation@workspace:.
└─ @datadog/datadog-ci@npm:2.10.0 (via npm:^2.9.1)
└─ proxy-agent@npm:5.0.0 (via npm:5.0.0)
└─ pac-proxy-agent@npm:5.0.0 (via npm:^5.0.0)
└─ pac-resolver@npm:5.0.1 (via npm:^5.0.0)
└─ degenerator@npm:3.0.2 (via npm:^3.0.2)
└─ vm2@npm:3.9.14 (via npm:^3.9.8)
```
That's because we only updated the `yarn.lock` in datadog-ci, and not the minimum required version in `package.json`.
This PR should fix:
- https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/5
- https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/8
- https://github.com/DataDog/datadog-ci-azure-devops/security/dependab …
> [dep] Upgrade `vm2` to `3.9.17`

- SyntheticsRunTestsTask/task.ts
To align with what's done [in the github action](https://github.com/DataDog/synthetics-ci-github-action/blob/bd6bed82af520d41473c4ce4e68bcb9ac4709dff/src/main.ts#L22-L26), this PR also sets the task result to a success with the summary.
> Set task result with summary when tests succeed

- azure-pipelines.yml
- ci/e2e.azure-pipelines.yml
This PR automates running **actual E2E tests** on the DEV extension ([defined here](https://github.com/DataDog/datadog-ci-azure-devops/blob/main/ci/e2e.azure-pipelines.yml)).
**Note:** what I will call "custom E2E tests" below is the following part of our main Azure DevOps (ADO) pipeline ([defined here](https://github.com/DataDog/datadog-ci-azure-devops/blob/main/azure-pipelines.yml)). Where we extract the VSIX, define inputs with environment variables and run the task with `node`:
https://github.com/DataDog/datadog-ci-azure-devops/blob/6ba15782b27091926f558214a89c5c355d4d80f2/azure-pipelines.yml#L116-L124
Before:
- Create a PR
- "Custom E2E tests" are run automatically on every commit in the PR
- To run the **actual E2E tests**, you had to:
1. Manually run the main ADO pipeline with …
> [ci] Trigger the E2E pipeline when the main ADO pipeline succeeds

- README.md
- SyntheticsRunTestsTask/__tests__/utils.test.ts
- SyntheticsRunTestsTask/resolve-config.ts
- SyntheticsRunTestsTask/task.json
- SyntheticsRunTestsTask/utils.ts
This PR adds a `pollingTimeout` input to be able to set a value of `pollingTimeout` different than the default of 30 minutes ([official documentation](https://docs.datadoghq.com/continuous_testing/cicd_integrations/configuration?tab=npm#global-configuration-file-options)).
This input must be an integer.
> Add `pollingTimeout` input

- SyntheticsRunTestsTask/__tests__/fixtures.ts
- SyntheticsRunTestsTask/__tests__/main.test.ts
- SyntheticsRunTestsTask/__tests__/mocks/polling-timeout.ts
- SyntheticsRunTestsTask/resolve-config.ts
This PR moves the `polling_timeout` input from the root of the config to the `global` field of the config, where it's expected by datadog-ci: 
datadog-ci pushes pollingTimeout from root config to global config if pollingTimeout is undefined in the global config
- the implementation: https://github.com/DataDog/datadog-ci/blob/8000318d70fd8af22b0e377b27078762b562efb7/src/commands/synthetics/command.ts#L228
- the test: https://github.com/DataDog/datadog-ci/blob/65ffde5d90474af5930da4c2faf016505b70bff9/src/commands/synthetics/__tests__/cli.test.ts#L173-L186
> [SYNTH-9893] move polling_timeout input to the global config field

- ci/e2e.config.json
The `timeout` option was removed a long time ago (cf. [here](https://github.com/DataDog/datadog-ci/blob/aed788742c95396eb3c898799dd64c712df2edb2/src/commands/synthetics/README.md) and [here](https://github.com/DataDog/datadog-ci/blob/aed788742c95396eb3c898799dd64c712df2edb2/src/commands/synthetics/run-test.ts#L58) to go back in time).
This PR updates the config to [the right  `pollingTimeout` config](https://github.com/DataDog/datadog-ci/blob/c6ce9dcf152521adb118c15b75434f645e22ab6a/src/commands/synthetics/run-test.ts#L156).
> [ci] Update config files

- SyntheticsRunTestsTask/__tests__/main.test.ts
- SyntheticsRunTestsTask/task.ts
- #74 ←
- #76 
---
This PR adds a deprecation notice to the `SyntheticsRunTests@0`, before we upgrade it to `SyntheticsRunTests@1`.
> Add deprecation notice for `SyntheticsRunTests@0`

- README.md
- SyntheticsRunTestsTask/__tests__/main.test.ts
- SyntheticsRunTestsTask/task.json
- SyntheticsRunTestsTask/task.ts
- vss-extension.json
**Recent updates:**
- The extension was renamed from `Datadog CI` to `Datadog Continuous Testing` (released in [`v1.4.1`](https://github.com/DataDog/datadog-ci-azure-devops/releases/tag/v1.4.1)).
- As of `v1.5.0`, the task will have to be referred to with `SyntheticsRunTests@1`
- Otherwise, `SyntheticsRunTests@0` will fall back to the last task that we published under this major version, i.e. `SyntheticsRunTests@0.1.5` (contributed in extension `v1.4.1`). And it will show a deprecation notice.
This PR [updates the README](https://github.com/DataDog/datadog-ci-azure-devops/blob/corentin.girard/release-1-5-0/README.md) to show a note saying that we recently went from `SyntheticsRunTests@0` to `SyntheticsRunTests@1`.
> Release `v1.5.0`

- .azure-pipelines/main-pipeline.yml
- ci/poll-dev-extension-availability.sh
Since we were using `npx tfx-cli`, this tool was downloaded again although it was already there on the disk, since it's downloaded with this task:
https://github.com/DataDog/datadog-ci-azure-devops/blob/26080d5be4b11e779937edb605c33368b422582a/.azure-pipelines/main-pipeline.yml#L150-L153
Downloading this tool with `npm` was showing useless warnings, which now don't appear anymore.
**Before:**
```
/usr/bin/bash /home/vsts/work/_temp/d605dd96-ff78-4f86-abf9-8b7c321e0b55.sh
npm WARN exec The following package was not found and will be installed: tfx-cli@0.15.0
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Installed …
```
> [ci] Use cached `tfx` tool

- .azure-pipelines/dev-pipeline.yml
- .azure-pipelines/release-pipeline.yml
After #73, we lost the DEV pipeline on the `main` branch. It's not ideal since it triggers the E2E tests, meaning that the `main` branch is not end-to-end tested anymore.
> [ci] Run dev pipeline on main branch

- README.md
We renamed the pipeline recently, so the status badge is outdated:
---
This PR updates the badge to be:
[![Build Status](https://dev.azure.com/datadog-ci/Datadog%20CI%20Azure%20DevOps%20Extension/_apis/build/status%2FDevelopment?branchName=main)](https://dev.azure.com/datadog-ci/Datadog%20CI%20Azure%20DevOps%20Extension/_build/latest?definitionId=4&branchName=main)
> [readme] Update pipeline status badge

- .github/workflows/unit-tests.yml
- SyntheticsRunTestsTask/__tests__/fixtures.ts
- SyntheticsRunTestsTask/package.json
- SyntheticsRunTestsTask/yarn.lock
Although [we target Node 16](https://github.com/DataDog/datadog-ci-azure-devops/blob/main/SyntheticsRunTestsTask/.node-version), we are still using Node 10 in the unit tests.
This now makes the CI fail because of the `?.` operator being used in JS. (see [failing CI job](https://github.com/DataDog/datadog-ci-azure-devops/actions/runs/5549088903/jobs/10132775647))
For the record, this operator was introduced when bumping `proxy-agent` in datadog-ci in https://github.com/DataDog/datadog-ci/pull/957. This package [targets Node 14](https://github.com/TooTallNate/proxy-agents/blob/d5cdaa1b774c699c75b543eb4b112290d261e321/packages/proxy-agent/package.json#L17).
This PR bumps `azure-pipelines-task-lib` to version 4 (which supports Node 16 - see …
> [test] Use Node 16 in unit tests

- SyntheticsRunTestsTask/package.json
- SyntheticsRunTestsTask/yarn.lock
Bump Jest to 29 to support modules (like axios), which [use the new `exports` property in package.json](https://github.com/axios/axios/blob/7009715369a50740ba2ce00534012c1caf269ad2/package.json#L7-L20).
This PR will fix the failing CI in https://github.com/DataDog/datadog-ci-azure-devops/pull/113.
```bash
● Test suite failed to run
Jest encountered an unexpected token
Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
By default "node_modules" folder is ignored by transformers.
Here's what you can do:
• If you are trying to use ECMAScript …
```
> [dep] Upgrade to Jest 29

- SyntheticsRunTestsTask/__tests__/fixtures.ts
- SyntheticsRunTestsTask/__tests__/main.test.ts
- SyntheticsRunTestsTask/jest.config.js
- SyntheticsRunTestsTask/package.json
- SyntheticsRunTestsTask/yarn.lock
This PR will [fix this issue](https://github.com/DataDog/datadog-ci-azure-devops/actions/runs/6828148182/job/18571726620#step:6:57):
This is caused by `azure-pipelines-task-lib`, which used to use `sync-request` (a way to synchronously make a request, which they use to [download Node.js before running the unit tests](https://github.com/DataDog/datadog-ci-azure-devops/actions/runs/6828148182/job/18571726620#step:6:38)).
This `sync-request` package is known for leaving orphan processes (https://github.com/ForbesLindesay/sync-request/issues/137) at import time and it recently had some vulnerabilities, which led Microsoft to remove this dependency (https://github.com/microsoft/azure-pipelines-task-lib/pull/932), hence the need to bump `azure-pipelines-task-lib`: 07464dd
> [test] Fix open handles in unit tests

- SyntheticsRunTestsTask/yarn.lock
Fixes https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/27
Fixes https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/25
Related to https://github.com/DataDog/datadog-ci/pull/1192
```
yarn set resolution socks@npm:^2.7.1 2.7.3
yarn set resolution pac-resolver@npm:^7.0.0 7.0.1
yarn set resolution node-gyp@npm:latest 10.0.1
yarn set resolution follow-redirects@npm:^1.15.1 1.15.5
```
> [dep] Fix `ip` and `follow-redirects` vulnerabilities

- README.md
Noticed that the in the wrong place in the usage examples o just doing a quick boy-scouting
> [NO-JIRA] Move variables to the correct example

- SyntheticsRunTestsTask/yarn.lock
Fix https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/29
> [dep] Bump protobufjs to `7.2.6`

- SyntheticsRunTestsTask/yarn.lock
Fix https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/30
> [dep] Bump tar to `6.2.1`

- README.md
- SyntheticsRunTestsTask/__tests__/main.test.ts
- SyntheticsRunTestsTask/resolve-config.ts
- SyntheticsRunTestsTask/task.json
- ci/e2e.config.json
See https://github.com/DataDog/datadog-ci/pull/1285
> Remove usage of deprecated `global`

- .github/workflows/bump-datadog-ci.yml
- .github/workflows/release-version.yml
Added the following line to the release instructions:
> **Important:** Please comment `/azp run` on the PR to run the Azure pipelines.
> [ci] Update release instructions

- SyntheticsRunTestsTask/yarn.lock
- https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/37
- https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/31
- https://github.com/DataDog/datadog-ci-azure-devops/security/dependabot/33
Commands I ran:
```sh
yarn set resolution cross-spawn@npm:^7.0.0 7.0.6
yarn set resolution google-gax@npm:^4.0.3 4.3.8
yarn set resolution braces@npm:^3.0.1 3.0.3
```
> [dep] Upgrade deps to fix 3 vulnerabilities

- SyntheticsRunTestsTask/task.json
In Azure DevOps, the default value is not only there for documentation: it's actually used as a fallback. This means that although the user didn't provide any `files` input, we are still asking datadog-ci to perform a glob file search.
> Remove default value for `files`

- .azure-pipelines/dev-pipeline.yml
- .azure-pipelines/e2e-pipeline.yml
- .azure-pipelines/release-pipeline.yml
- .github/workflows/unit-tests.yml
- ci/increment-version.sh
This PR makes sure we bump the referenced task version in e2e tests when doing a major bump on the integration. Otherwise, we'd still target the old major version.
This PR also does a few clean ups.
> [chores] Bump pinned e2e task version on major bump

- .azure-pipelines/dev-pipeline.yml
- .azure-pipelines/e2e-pipeline.yml
- .azure-pipelines/release-pipeline.yml
- .github/workflows/unit-tests.yml
- SyntheticsRunTestsTask/__tests__/fixtures.ts
- SyntheticsRunTestsTask/__tests__/scenarios/api-keys.ts
- SyntheticsRunTestsTask/__tests__/scenarios/junit-report.ts
- SyntheticsRunTestsTask/__tests__/scenarios/polling-timeout.ts
- SyntheticsRunTestsTask/__tests__/scenarios/service-connection-env-vars.ts
- SyntheticsRunTestsTask/__tests__/scenarios/service-connection-misconfigured.ts
- SyntheticsRunTestsTask/__tests__/scenarios/service-connection.ts
- ci/increment-version.sh
- https://github.com/DataDog/datadog-ci-azure-devops/pull/217 (← **you are here**)
- https://github.com/DataDog/datadog-ci-azure-devops/pull/215
Mock `getOrgSettings` so it doesn't fail and retry 3 times, speeding up test scenarios.
> [chores] Speed up unit tests by mocking `getOrgSettings`

- .azure-pipelines/e2e-pipeline.yml
- README.md
- SyntheticsRunTestsTask/__tests__/fixtures.ts
- SyntheticsRunTestsTask/__tests__/main.test.ts
- SyntheticsRunTestsTask/__tests__/scenarios/api-keys.ts
- SyntheticsRunTestsTask/task.ts
- https://github.com/DataDog/datadog-ci-azure-devops/pull/217
- https://github.com/DataDog/datadog-ci-azure-devops/pull/215 (← **you are here**)
Like https://github.com/DataDog/synthetics-ci-github-action/pull/309, we want to expose outputs to other Azure DevOps tasks too.
> [SYNTH-19621] Expose variables to other tasks

- .azure-pipelines/e2e-pipeline.yml
This PR splits the "Example of using outputs" e2e step into 2 different implementations that are OS-specific.
Since the `rawResults` output is a JSON string which has a varying size based on a lot of factors, the "Example of using outputs" e2e step was flaky, and failed today with:
On Linux the command line length limit is huge (~1 or 2 millions of characters) but it's 8191 on Windows.
So the solution is to store the `$(runSyntheticsTests.rawResults)` inside an env var that can be used later in the powershell script. I preferred to keep the original example for Linux because it works with less code.
> [ci] Fix flaky e2e test on Windows
